# Generated by Django 4.2.6 on 2024-12-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='логин')),
                ('name', models.CharField(max_length=150, verbose_name='фио')),
                ('date_of_b', models.DateField(verbose_name='дата рождения')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('doctor', 'Врач'), ('parent', 'Родитель'), ('child', 'Ребёнок')], default='child', max_length=20)),
                ('password', models.CharField(max_length=150, verbose_name='пароль')),
                ('is_auth', models.BooleanField(default=False)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.cusers')),
                ('doctor_children', models.ManyToManyField(blank=True, related_name='doctors', to='accounts.cusers')),
            ],
            options={
                'verbose_name': 'Пользовательй',
                'verbose_name_plural': 'Пользователий',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
