# Generated by Django 4.2.6 on 2024-12-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_choice_dialog_game_painting_gamescore_cusers_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
        migrations.AlterModelOptions(
            name='cusers',
            options={},
        ),
        migrations.RemoveField(
            model_name='cusers',
            name='games',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
