# Generated by Django 4.2.6 on 2024-12-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_choice_delete_dialog_remove_gamescore_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('joy', models.IntegerField(default=0)),
                ('sorrow', models.IntegerField(default=0)),
                ('love', models.IntegerField(default=0)),
                ('anger', models.IntegerField(default=0)),
                ('boredom', models.IntegerField(default=0)),
                ('happiness', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='accounts.cusers')),
            ],
            options={
                'verbose_name': 'Результат игры',
                'verbose_name_plural': 'Результаты игр',
                'ordering': ['-date'],
            },
        ),
    ]
