# Generated by Django 4.2.6 on 2024-12-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gameresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('Painting', 'Раскраска'), ('Dialog', 'Диалог'), ('Choice', 'Выбор')], max_length=20),
        ),
    ]
