# Generated by Django 4.2.6 on 2024-12-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_gameresult_user_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cusers'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='text',
            field=models.TextField(),
        ),
    ]
