# Generated by Django 4.2.6 on 2024-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_prescription_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date_created'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='prescription',
            name='text',
            field=models.TextField(verbose_name='Текст рецепта'),
        ),
    ]
