# Generated by Django 6.0.2 on 2026-02-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_duplicate_usernames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date_created'], 'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterField(
            model_name='behaviorpattern',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='behaviorpattern',
            name='fuzzy_sets',
            field=models.JSONField(default=dict, verbose_name='нечёткие множества'),
        ),
        migrations.AlterField(
            model_name='behaviorpattern',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='behaviorpattern',
            name='pattern_type',
            field=models.CharField(choices=[('strategy', 'Стратегия решения'), ('attention', 'Внимание'), ('emotion', 'Эмоциональная реакция'), ('social', 'Социальное поведение')], max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='behaviorpattern',
            name='relevant_games',
            field=models.JSONField(default=list, verbose_name='соответствующие игры'),
        ),
        migrations.AlterField(
            model_name='cusers',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='diagnosticprofile',
            name='cognitive_style',
            field=models.CharField(blank=True, choices=[('systematic', 'Систематический'), ('impulsive', 'Импульсивный'), ('adaptive', 'Адаптивный'), ('chaotic', 'Хаотичный')], max_length=50, verbose_name='когнитивный стиль'),
        ),
        migrations.AlterField(
            model_name='diagnosticprofile',
            name='emotional_profile',
            field=models.JSONField(default=dict, verbose_name='эмоциональный профиль'),
        ),
        migrations.AlterField(
            model_name='diagnosticprofile',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='рекомендации'),
        ),
        migrations.AlterField(
            model_name='fuzzyinferencerule',
            name='conclusion',
            field=models.TextField(verbose_name='заключение'),
        ),
        migrations.AlterField(
            model_name='fuzzyinferencerule',
            name='condition',
            field=models.JSONField(verbose_name='условие'),
        ),
        migrations.AlterField(
            model_name='fuzzyinferencerule',
            name='confidence',
            field=models.FloatField(default=1.0, verbose_name='уверенность'),
        ),
        migrations.AlterField(
            model_name='fuzzyinferencerule',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='fuzzyinferencerule',
            name='recommendation',
            field=models.TextField(verbose_name='рекомендация'),
        ),
        migrations.AlterField(
            model_name='fuzzymembershipfunction',
            name='method_class',
            field=models.CharField(choices=[('traditional_test', 'Стандартизированный тест'), ('projective', 'Проективный метод'), ('observation', 'Наблюдение'), ('digital_game', 'Цифровая игра'), ('hybrid', 'Гибридный метод')], max_length=50, verbose_name='класс метода'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='accounts.cusers'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, verbose_name='дозировка'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='название препарата'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('medication', 'Лекарство'), ('therapy', 'Терапия'), ('exercise', 'Упражнение'), ('recommendation', 'Рекомендация')], default='recommendation', max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='text',
            field=models.TextField(verbose_name='текст назначения'),
        ),
    ]
