# Generated by Django 6.0.2 on 2026-02-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_cusers_options_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('Painting', 'Раскраска'), ('Dialog', 'Диалог'), ('Choice', 'Выбор'), ('Memory', 'Память'), ('Puzzle', 'Головоломка'), ('Sequence', 'Последовательность')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('Painting', 'Раскраска'), ('Dialog', 'Диалог'), ('Choice', 'Выбор'), ('Puzzle', 'Головоломка'), ('Memory', 'Память'), ('Sequence', 'Последовательность'), ('Adventure', 'Приключение')], max_length=20),
        ),
    ]
