# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_new_game_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('Painting', 'Раскраска'), ('Dialog', 'Эмоциональный диалог'), ('Choice', 'Эмоциональные сценарии'), ('Memory', 'Память'), ('Puzzle', 'Головоломка'), ('Sequence', 'Последовательность'), ('EmotionFace', 'Узнай эмоцию'), ('Attention', 'Внимание'), ('GoNoGo', 'Стоп-игра'), ('Sort', 'Сортировка'), ('Pattern', 'Паттерн'), ('EmotionMatch', 'Эмоция и ситуация')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('Painting', 'Раскраска'), ('Dialog', 'Эмоциональный диалог'), ('Choice', 'Эмоциональные сценарии'), ('Memory', 'Память'), ('Puzzle', 'Головоломка'), ('Sequence', 'Последовательность'), ('EmotionFace', 'Узнай эмоцию'), ('Attention', 'Внимание'), ('GoNoGo', 'Стоп-игра'), ('Sort', 'Сортировка'), ('Pattern', 'Паттерн'), ('EmotionMatch', 'Эмоция и ситуация')], max_length=20),
        ),
    ]
